import { ImageSourcePropType } from "react-native";

export interface Product {
  id: number;
  for: "Men" | "Woman";
  category: "Clothing" | "Shoes";
  type: "Shirt" | "Jeans" | "Sneaker";
  brand: string;
  color: string;
  title: string;
  price: string;
  salePrice: string;
  salePercent?: string;
  isSale: boolean;
  isFavorite: boolean;
  isFeatured: boolean;
  img: ImageSourcePropType;
}

export const products: Product[] = [
  {
    id: 1,
    for: "Men",
    category: "Clothing",
    type: "Shirt",
    brand: "Jack & Jones",
    color: "crockery/beige",
    title: "JPRBLASUMMER BAND",
    price: "$40",
    salePrice: "",
    isSale: false,
    isFavorite: true,
    isFeatured: true,
    img: require("../assets/clothing1.jpeg"),
  },
  {
    id: 2,
    for: "Men",
    category: "Clothing",
    type: "Shirt",
    brand: "Auden Cavill",
    color: "green",
    title: "MARVIC",
    price: "$60",
    salePrice: "$40",
    salePercent: "-33%",
    isSale: true,
    isFavorite: true,
    isFeatured: false,
    img: require("../assets/clothing2.jpeg"),
  },
  {
    id: 3,
    for: "Woman",
    category: "Clothing",
    type: "Shirt",
    brand: "Massimo Dutti",
    color: "white",
    title: "",
    price: "$50",
    salePrice: "",
    isSale: false,
    isFavorite: true,
    isFeatured: false,
    img: require("../assets/clothing3.jpeg"),
  },
  {
    id: 4,
    for: "Woman",
    category: "Clothing",
    type: "Shirt",
    brand: "Seidensticker",
    color: "white",
    title: "Comfortable Slim",
    price: "$70",
    salePrice: "$50",
    salePercent: "-28%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/clothing4.jpeg"),
  },
  {
    id: 5,
    for: "Men",
    category: "Clothing",
    type: "Jeans",
    brand: "Pull & Bear",
    color: "blue/grey",
    title: "Relaxed Fit",
    price: "$35",
    salePrice: "",
    isSale: false,
    isFavorite: false,
    isFeatured: true,
    img: require("../assets/clothing5.jpeg"),
  },
  {
    id: 6,
    for: "Men",
    category: "Clothing",
    type: "Jeans",
    brand: "Tom Tailor",
    color: "black denim",
    title: "TROY - Slim Fit",
    price: "$50",
    salePrice: "$40",
    salePercent: "-20%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/clothing6.jpeg"),
  },
  {
    id: 7,
    for: "Woman",
    category: "Clothing",
    type: "Jeans",
    brand: "Bershka",
    color: "dark/blue",
    title: "Straight Leg",
    price: "$30",
    salePrice: "",
    isSale: false,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/clothing7.jpeg"),
  },
  {
    id: 8,
    for: "Woman",
    category: "Clothing",
    type: "Jeans",
    brand: "G-Star",
    color: "indigo aged",
    title: "KATE BOYFRIEND - Relaxed Fit",
    price: "$100",
    salePrice: "$70",
    salePercent: "-30%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/clothing8.jpeg"),
  },
  {
    id: 9,
    for: "Men",
    category: "Shoes",
    type: "Sneaker",
    brand: "Vans",
    color: "black",
    title: "OLD SKOOL",
    price: "$75",
    salePrice: "",
    isSale: false,
    isFavorite: false,
    isFeatured: true,
    img: require("../assets/sneaker1.jpeg"),
  },
  {
    id: 10,
    for: "Men",
    category: "Shoes",
    type: "Sneaker",
    brand: "New Balance",
    color: "green",
    title: "500",
    price: "$75",
    salePrice: "$55",
    salePercent: "-26%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/sneaker2.jpeg"),
  },
  {
    id: 11,
    for: "Woman",
    category: "Shoes",
    type: "Sneaker",
    brand: "Nike",
    color: "black/anthracite/white",
    title: "AIR MAX 270",
    price: "$150",
    salePrice: "",
    isSale: false,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/sneaker3.jpeg"),
  },
  {
    id: 12,
    for: "Woman",
    category: "Shoes",
    type: "Sneaker",
    brand: "Converse",
    color: "black/garnet/white",
    title: "CHUCK TAYLOR ALL STAR LIFT",
    price: "$80",
    salePrice: "$75",
    salePercent: "-6%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/sneaker4.jpeg"),
  },
];
