import { ImageSourcePropType } from "react-native";

export type ClothingSize = "XS" | "S" | "M" | "L" | "XL" | "XXL";
export type ShoeSize = "38" | "39" | "40" | "41" | "42" | "43" | "44" | "45";
export type Gender = "Men" | "Woman";
export type Category = "Clothing" | "Shoes";
export type ProductType = "Shirt" | "Jeans" | "Sneaker";

export interface Product {
  id: number;
  for: Gender;
  category: Category;
  type: ProductType;
  brand: string;
  color: string;
  title: string;
  price: string;
  salePrice: string;
  salePercent?: string;
  isSale: boolean;
  isFavorite: boolean;
  isFeatured: boolean;
  img: ImageSourcePropType;
  sizes: ClothingSize[] | ShoeSize[];
}

export const products: Product[] = [
  {
    id: 1,
    for: "Men",
    category: "Clothing",
    type: "Shirt",
    brand: "Jack & Jones",
    color: "crockery/beige",
    title: "JPRBLASUMMER BAND",
    price: "$40",
    salePrice: "",
    isSale: false,
    isFavorite: false,
    isFeatured: true,
    img: require("../assets/images/clothing1.jpeg"),
    sizes: ["S", "M", "L"],
  },
  {
    id: 2,
    for: "Men",
    category: "Clothing",
    type: "Shirt",
    brand: "Auden Cavill",
    color: "green",
    title: "MARVIC",
    price: "$60",
    salePrice: "$40",
    salePercent: "-33%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/images/clothing2.jpeg"),
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 3,
    for: "Woman",
    category: "Clothing",
    type: "Shirt",
    brand: "Massimo Dutti",
    color: "white",
    title: "Join Life",
    price: "$50",
    salePrice: "",
    isSale: false,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/images/clothing3.jpeg"),
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 4,
    for: "Woman",
    category: "Clothing",
    type: "Shirt",
    brand: "Seidensticker",
    color: "white",
    title: "Comfortable Slim",
    price: "$70",
    salePrice: "$50",
    salePercent: "-28%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/images/clothing4.jpeg"),
    sizes: ["S", "M", "L"],
  },
  {
    id: 5,
    for: "Men",
    category: "Clothing",
    type: "Jeans",
    brand: "Pull & Bear",
    color: "blue/grey",
    title: "Relaxed Fit",
    price: "$35",
    salePrice: "",
    isSale: false,
    isFavorite: false,
    isFeatured: true,
    img: require("../assets/images/clothing5.jpeg"),
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 6,
    for: "Men",
    category: "Clothing",
    type: "Jeans",
    brand: "Tom Tailor",
    color: "black denim",
    title: "TROY - Slim Fit",
    price: "$50",
    salePrice: "$40",
    salePercent: "-20%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/images/clothing6.jpeg"),
    sizes: ["S", "M", "L"],
  },
  {
    id: 7,
    for: "Woman",
    category: "Clothing",
    type: "Jeans",
    brand: "Bershka",
    color: "dark/blue",
    title: "Straight Leg",
    price: "$30",
    salePrice: "",
    isSale: false,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/images/clothing7.jpeg"),
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 8,
    for: "Woman",
    category: "Clothing",
    type: "Jeans",
    brand: "G-Star",
    color: "indigo aged",
    title: "KATE BOYFRIEND - Relaxed Fit",
    price: "$100",
    salePrice: "$70",
    salePercent: "-30%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/images/clothing8.jpeg"),
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: 9,
    for: "Men",
    category: "Shoes",
    type: "Sneaker",
    brand: "Vans",
    color: "black",
    title: "OLD SKOOL",
    price: "$75",
    salePrice: "",
    isSale: false,
    isFavorite: false,
    isFeatured: true,
    img: require("../assets/images/sneaker1.jpeg"),
    sizes: ["40", "41", "42", "43", "44", "45"],
  },
  {
    id: 10,
    for: "Men",
    category: "Shoes",
    type: "Sneaker",
    brand: "New Balance",
    color: "green",
    title: "500",
    price: "$75",
    salePrice: "$55",
    salePercent: "-26%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/images/sneaker2.jpeg"),
    sizes: ["40", "41", "42", "43", "44", "45"],
  },
  {
    id: 11,
    for: "Woman",
    category: "Shoes",
    type: "Sneaker",
    brand: "Nike",
    color: "black/anthracite/white",
    title: "AIR MAX 270",
    price: "$150",
    salePrice: "",
    isSale: false,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/images/sneaker3.jpeg"),
    sizes: ["38", "39", "40", "41", "42", "43"],
  },
  {
    id: 12,
    for: "Woman",
    category: "Shoes",
    type: "Sneaker",
    brand: "Converse",
    color: "black/garnet/white",
    title: "CHUCK TAYLOR ALL STAR LIFT",
    price: "$80",
    salePrice: "$75",
    salePercent: "-6%",
    isSale: true,
    isFavorite: false,
    isFeatured: false,
    img: require("../assets/images/sneaker4.jpeg"),
    sizes: ["38", "39", "40", "41", "42", "43"],
  },
];
