export const categories = [
  {
    id: 1,
    name: 'Clothing',
    products: [
      {
        id: 1,
        for: 'Men',
        type: 'Shirt',
        brand: 'Jack & Jones',
        color: 'crockery/beige',
        title: 'JPRBLASUMMER BAND',
        price: '$40',
        salePrice: '',
        isSale: false,
        isFavorite: false,
        isFeatured: true,
        img: 'clothing1.jpeg',
      },
      {
        id: 2,
        for: 'Men',
        type: 'Shirt',
        brand: 'Auden Cavill',
        color: 'green',
        title: 'MARVIC',
        price: '$60',
        salePrice: '$40',
        isSale: true,
        isFavorite: false,
        isFeatured: false,
        img: 'clothing2.jpeg',
      },
      {
        id: 3,
        for: 'Woman',
        type: 'Shirt',
        brand: 'Massimo Dutti',
        color: 'white',
        title: '',
        price: '$50',
        salePrice: '',
        isSale: false,
        isFavorite: false,
        isFeatured: false,
        img: 'clothing3.jpeg',
      },
      {
        id: 4,
        for: 'Woman',
        type: 'Shirt',
        brand: 'Seidensticker',
        color: 'white',
        title: 'Comfortable Slim',
        price: '$70',
        salePrice: '$50',
        isSale: true,
        isFavorite: false,
        isFeatured: false,
        img: 'clothing4.jpeg',
      },
      {
        id: 5,
        for: 'Men',
        type: 'Jeans',
        brand: 'Pull & Bear',
        color: 'blue/grey',
        title: 'Relaxed Fit',
        price: '$35',
        salePrice: '',
        isSale: false,
        isFavorite: false,
        isFeatured: false,
        img: 'clothing5.jpeg',
      },
      {
        id: 6,
        for: 'Men',
        type: 'Jeans',
        brand: 'Tom Tailor',
        color: 'black denim',
        title: 'TROY - Slim Fit',
        price: '$50',
        salePrice: '$40',
        isSale: true,
        isFavorite: false,
        isFeatured: false,
        img: 'clothing6.jpeg',
      },
      {
        id: 7,
        for: 'Woman',
        type: 'Jeans',
        brand: 'Bershka',
        color: 'dark/blue',
        title: 'Straight Leg',
        price: '$30',
        salePrice: '',
        isSale: false,
        isFavorite: false,
        isFeatured: false,
        img: 'clothing7.jpeg',
      },
      {
        id: 8,
        for: 'Woman',
        type: 'Jeans',
        brand: 'G-Star',
        color: 'indigo aged',
        title: 'KATE BOYFRIEND - Relaxed Fit',
        price: '$100',
        salePrice: '$70',
        isSale: true,
        isFavorite: false,
        isFeatured: false,
        img: 'clothing8.jpeg',
      },
    ],
  },
  {
    id: 2,
    name: 'Shoes',
    products: [
      {
        id: 1,
        for: 'Men',
        type: 'Sneaker',
        brand: 'Vans',
        color: 'black',
        title: 'OLD SKOOL',
        price: '$75',
        salePrice: '',
        isSale: false,
        isFavorite: false,
        isFeatured: true,
        img: 'sneaker1.jpeg',
      },
      {
        id: 2,
        for: 'Men',
        type: 'Sneaker',
        brand: 'New Balance',
        color: 'green',
        title: '500',
        price: '$75',
        salePrice: '$55',
        isSale: true,
        isFavorite: false,
        isFeatured: false,
        img: 'sneaker2.jpeg',
      },
      {
        id: 3,
        for: 'Woman',
        type: 'Sneaker',
        brand: 'Nike',
        color: 'black/anthracite/white',
        title: 'AIR MAX 270',
        price: '$150',
        salePrice: '',
        isSale: false,
        isFavorite: false,
        isFeatured: false,
        img: 'sneaker3.jpeg',
      },
      {
        id: 4,
        for: 'Woman',
        type: 'Sneaker',
        brand: 'Converse',
        color: 'black/garnet/white',
        title: 'CHUCK TAYLOR ALL STAR LIFT',
        price: '$80',
        salePrice: '$75',
        isSale: true,
        isFavorite: false,
        isFeatured: false,
        img: 'sneaker4.jpeg',
      },
    ],
  },
];
